package life.lixiaoyu.composeactionlearning.chapter1

import android.content.Intent
import android.os.Bundle
import androidx.activity.ComponentActivity
import androidx.activity.compose.setContent
import androidx.compose.foundation.layout.Column
import androidx.compose.runtime.Composable
import androidx.compose.ui.platform.LocalContext
import life.lixiaoyu.composeactionlearning.FullPageWrapper
import life.lixiaoyu.composeactionlearning.ItemButton

class Chapter1Activity : ComponentActivity() {
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            FullPageWrapper {
                Chapter1Page()
            }
        }
    }
}

@Composable
fun Chapter1Page() {
    Column {
        val context = LocalContext.current
        Column {
            ItemButton(text = "Default Hello World Activity generated by AS") {
                context.startActivity(Intent(context, HelloWorldActivity::class.java))
            }
            ItemButton(text = "Add Compose to View System") {
                context.startActivity(Intent(context, AddComposeToViewActivity::class.java))
            }
            ItemButton(text = "Add WebView to Compose System") {
                context.startActivity(Intent(context, AddViewToComposeActivity::class.java))
            }
            ItemButton(text = "Add XML View to Compose System") {
                context.startActivity(Intent(context, AddXMLViewToComposeActivity::class.java))
            }
        }
    }
}